//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanlyKiluat
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Quanlykiluat1Entities : DbContext
    {
        public Quanlykiluat1Entities()
            : base("name=Quanlykiluat1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Daidoi> Daidois { get; set; }
        public virtual DbSet<giamsat> giamsats { get; set; }
        public virtual DbSet<Hocvien> Hocviens { get; set; }
        public virtual DbSet<HocVien_Phanloaikiluat> HocVien_Phanloaikiluat { get; set; }
        public virtual DbSet<Hocvien_Phanloairenluyen> Hocvien_Phanloairenluyen { get; set; }
        public virtual DbSet<Lop> Lops { get; set; }
        public virtual DbSet<Phanloaikiluat> Phanloaikiluats { get; set; }
        public virtual DbSet<Phanloairenluyen> Phanloairenluyens { get; set; }
        public virtual DbSet<Quanly> Quanlies { get; set; }
        public virtual DbSet<Quychuan> Quychuans { get; set; }
    
        public virtual ObjectResult<string> getHocvien(string maHV)
        {
            var maHVParameter = maHV != null ?
                new ObjectParameter("MaHV", maHV) :
                new ObjectParameter("MaHV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("getHocvien", maHVParameter);
        }
    
        public virtual ObjectResult<string> getmaplkl()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("getmaplkl");
        }
    
        public virtual ObjectResult<string> getmaplrl()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("getmaplrl");
        }
    
        public virtual int insert_HVKL(string mahv_plkl, Nullable<System.DateTime> thoigian, string maHV, string maPLKL, string capdanhgia, string nguoidanhgia, Nullable<int> diemkiluat, Nullable<int> diemhoctap, Nullable<int> diemloisong, Nullable<int> diemhoatdongdoan)
        {
            var mahv_plklParameter = mahv_plkl != null ?
                new ObjectParameter("Mahv_plkl", mahv_plkl) :
                new ObjectParameter("Mahv_plkl", typeof(string));
    
            var thoigianParameter = thoigian.HasValue ?
                new ObjectParameter("Thoigian", thoigian) :
                new ObjectParameter("Thoigian", typeof(System.DateTime));
    
            var maHVParameter = maHV != null ?
                new ObjectParameter("MaHV", maHV) :
                new ObjectParameter("MaHV", typeof(string));
    
            var maPLKLParameter = maPLKL != null ?
                new ObjectParameter("MaPLKL", maPLKL) :
                new ObjectParameter("MaPLKL", typeof(string));
    
            var capdanhgiaParameter = capdanhgia != null ?
                new ObjectParameter("Capdanhgia", capdanhgia) :
                new ObjectParameter("Capdanhgia", typeof(string));
    
            var nguoidanhgiaParameter = nguoidanhgia != null ?
                new ObjectParameter("Nguoidanhgia", nguoidanhgia) :
                new ObjectParameter("Nguoidanhgia", typeof(string));
    
            var diemkiluatParameter = diemkiluat.HasValue ?
                new ObjectParameter("Diemkiluat", diemkiluat) :
                new ObjectParameter("Diemkiluat", typeof(int));
    
            var diemhoctapParameter = diemhoctap.HasValue ?
                new ObjectParameter("Diemhoctap", diemhoctap) :
                new ObjectParameter("Diemhoctap", typeof(int));
    
            var diemloisongParameter = diemloisong.HasValue ?
                new ObjectParameter("Diemloisong", diemloisong) :
                new ObjectParameter("Diemloisong", typeof(int));
    
            var diemhoatdongdoanParameter = diemhoatdongdoan.HasValue ?
                new ObjectParameter("Diemhoatdongdoan", diemhoatdongdoan) :
                new ObjectParameter("Diemhoatdongdoan", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insert_HVKL", mahv_plklParameter, thoigianParameter, maHVParameter, maPLKLParameter, capdanhgiaParameter, nguoidanhgiaParameter, diemkiluatParameter, diemhoctapParameter, diemloisongParameter, diemhoatdongdoanParameter);
        }
    
        public virtual int insert_HVRL(string mahv_plrl, Nullable<System.DateTime> thoigian, string maHV, string maPLRL, string maGS, Nullable<double> boi, Nullable<double> chaydai, Nullable<double> chayngan, Nullable<double> nhayxa, Nullable<int> xa)
        {
            var mahv_plrlParameter = mahv_plrl != null ?
                new ObjectParameter("Mahv_plrl", mahv_plrl) :
                new ObjectParameter("Mahv_plrl", typeof(string));
    
            var thoigianParameter = thoigian.HasValue ?
                new ObjectParameter("Thoigian", thoigian) :
                new ObjectParameter("Thoigian", typeof(System.DateTime));
    
            var maHVParameter = maHV != null ?
                new ObjectParameter("MaHV", maHV) :
                new ObjectParameter("MaHV", typeof(string));
    
            var maPLRLParameter = maPLRL != null ?
                new ObjectParameter("MaPLRL", maPLRL) :
                new ObjectParameter("MaPLRL", typeof(string));
    
            var maGSParameter = maGS != null ?
                new ObjectParameter("MaGS", maGS) :
                new ObjectParameter("MaGS", typeof(string));
    
            var boiParameter = boi.HasValue ?
                new ObjectParameter("Boi", boi) :
                new ObjectParameter("Boi", typeof(double));
    
            var chaydaiParameter = chaydai.HasValue ?
                new ObjectParameter("Chaydai", chaydai) :
                new ObjectParameter("Chaydai", typeof(double));
    
            var chaynganParameter = chayngan.HasValue ?
                new ObjectParameter("Chayngan", chayngan) :
                new ObjectParameter("Chayngan", typeof(double));
    
            var nhayxaParameter = nhayxa.HasValue ?
                new ObjectParameter("nhayxa", nhayxa) :
                new ObjectParameter("nhayxa", typeof(double));
    
            var xaParameter = xa.HasValue ?
                new ObjectParameter("xa", xa) :
                new ObjectParameter("xa", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insert_HVRL", mahv_plrlParameter, thoigianParameter, maHVParameter, maPLRLParameter, maGSParameter, boiParameter, chaydaiParameter, chaynganParameter, nhayxaParameter, xaParameter);
        }
    
        public virtual ObjectResult<spgetMaLop_Result> spgetMaLop(string maLop)
        {
            var maLopParameter = maLop != null ?
                new ObjectParameter("MaLop", maLop) :
                new ObjectParameter("MaLop", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spgetMaLop_Result>("spgetMaLop", maLopParameter);
        }
    
        public virtual ObjectResult<spgetMaQl_Result> spgetMaQl(string maQL)
        {
            var maQLParameter = maQL != null ?
                new ObjectParameter("MaQL", maQL) :
                new ObjectParameter("MaQL", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spgetMaQl_Result>("spgetMaQl", maQLParameter);
        }
    
        public virtual ObjectResult<spgetTableAllLop_Result> spgetTableAllLop()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spgetTableAllLop_Result>("spgetTableAllLop");
        }
    
        public virtual ObjectResult<spgetTableAN_Result> spgetTableAN()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spgetTableAN_Result>("spgetTableAN");
        }
    
        public virtual ObjectResult<spgetTableBD_Result> spgetTableBD()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spgetTableBD_Result>("spgetTableBD");
        }
    
        public virtual ObjectResult<spgetTableCNTT2_Result> spgetTableCNTT2()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spgetTableCNTT2_Result>("spgetTableCNTT2");
        }
    
        public virtual ObjectResult<spgettablegiamsat_Result> spgettablegiamsat()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spgettablegiamsat_Result>("spgettablegiamsat");
        }
    
        public virtual ObjectResult<spgetTableHVLop_Result> spgetTableHVLop(string malop)
        {
            var malopParameter = malop != null ?
                new ObjectParameter("Malop", malop) :
                new ObjectParameter("Malop", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spgetTableHVLop_Result>("spgetTableHVLop", malopParameter);
        }
    
        public virtual ObjectResult<spgettableplkl_Result> spgettableplkl()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spgettableplkl_Result>("spgettableplkl");
        }
    
        public virtual ObjectResult<spgettableplrl_Result> spgettableplrl()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spgettableplrl_Result>("spgettableplrl");
        }
    
        public virtual ObjectResult<spgettablequychuanKL_Result> spgettablequychuanKL()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spgettablequychuanKL_Result>("spgettablequychuanKL");
        }
    
        public virtual ObjectResult<spgettablequychuanRl_Result> spgettablequychuanRl()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spgettablequychuanRl_Result>("spgettablequychuanRl");
        }
    
        public virtual int update_HVKL(string mahv_plkl, Nullable<System.DateTime> thoigian, string maHV, string maPLKL, string capdanhgia, string nguoidanhgia, Nullable<int> diemkiluat, Nullable<int> diemhoctap, Nullable<int> diemloisong, Nullable<int> diemhoatdongdoan)
        {
            var mahv_plklParameter = mahv_plkl != null ?
                new ObjectParameter("Mahv_plkl", mahv_plkl) :
                new ObjectParameter("Mahv_plkl", typeof(string));
    
            var thoigianParameter = thoigian.HasValue ?
                new ObjectParameter("Thoigian", thoigian) :
                new ObjectParameter("Thoigian", typeof(System.DateTime));
    
            var maHVParameter = maHV != null ?
                new ObjectParameter("MaHV", maHV) :
                new ObjectParameter("MaHV", typeof(string));
    
            var maPLKLParameter = maPLKL != null ?
                new ObjectParameter("MaPLKL", maPLKL) :
                new ObjectParameter("MaPLKL", typeof(string));
    
            var capdanhgiaParameter = capdanhgia != null ?
                new ObjectParameter("Capdanhgia", capdanhgia) :
                new ObjectParameter("Capdanhgia", typeof(string));
    
            var nguoidanhgiaParameter = nguoidanhgia != null ?
                new ObjectParameter("Nguoidanhgia", nguoidanhgia) :
                new ObjectParameter("Nguoidanhgia", typeof(string));
    
            var diemkiluatParameter = diemkiluat.HasValue ?
                new ObjectParameter("Diemkiluat", diemkiluat) :
                new ObjectParameter("Diemkiluat", typeof(int));
    
            var diemhoctapParameter = diemhoctap.HasValue ?
                new ObjectParameter("Diemhoctap", diemhoctap) :
                new ObjectParameter("Diemhoctap", typeof(int));
    
            var diemloisongParameter = diemloisong.HasValue ?
                new ObjectParameter("Diemloisong", diemloisong) :
                new ObjectParameter("Diemloisong", typeof(int));
    
            var diemhoatdongdoanParameter = diemhoatdongdoan.HasValue ?
                new ObjectParameter("Diemhoatdongdoan", diemhoatdongdoan) :
                new ObjectParameter("Diemhoatdongdoan", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("update_HVKL", mahv_plklParameter, thoigianParameter, maHVParameter, maPLKLParameter, capdanhgiaParameter, nguoidanhgiaParameter, diemkiluatParameter, diemhoctapParameter, diemloisongParameter, diemhoatdongdoanParameter);
        }
    
        public virtual int update_HVRL(string mahv_plrl, Nullable<System.DateTime> thoigian, string maHV, string maPLRL, string maGS, Nullable<double> boi, Nullable<double> chaydai, Nullable<double> chayngan, Nullable<double> nhayxa, Nullable<int> xa)
        {
            var mahv_plrlParameter = mahv_plrl != null ?
                new ObjectParameter("Mahv_plrl", mahv_plrl) :
                new ObjectParameter("Mahv_plrl", typeof(string));
    
            var thoigianParameter = thoigian.HasValue ?
                new ObjectParameter("Thoigian", thoigian) :
                new ObjectParameter("Thoigian", typeof(System.DateTime));
    
            var maHVParameter = maHV != null ?
                new ObjectParameter("MaHV", maHV) :
                new ObjectParameter("MaHV", typeof(string));
    
            var maPLRLParameter = maPLRL != null ?
                new ObjectParameter("MaPLRL", maPLRL) :
                new ObjectParameter("MaPLRL", typeof(string));
    
            var maGSParameter = maGS != null ?
                new ObjectParameter("MaGS", maGS) :
                new ObjectParameter("MaGS", typeof(string));
    
            var boiParameter = boi.HasValue ?
                new ObjectParameter("Boi", boi) :
                new ObjectParameter("Boi", typeof(double));
    
            var chaydaiParameter = chaydai.HasValue ?
                new ObjectParameter("Chaydai", chaydai) :
                new ObjectParameter("Chaydai", typeof(double));
    
            var chaynganParameter = chayngan.HasValue ?
                new ObjectParameter("Chayngan", chayngan) :
                new ObjectParameter("Chayngan", typeof(double));
    
            var nhayxaParameter = nhayxa.HasValue ?
                new ObjectParameter("nhayxa", nhayxa) :
                new ObjectParameter("nhayxa", typeof(double));
    
            var xaParameter = xa.HasValue ?
                new ObjectParameter("xa", xa) :
                new ObjectParameter("xa", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("update_HVRL", mahv_plrlParameter, thoigianParameter, maHVParameter, maPLRLParameter, maGSParameter, boiParameter, chaydaiParameter, chaynganParameter, nhayxaParameter, xaParameter);
        }
    
        public virtual int insert_giamsat(string mags, string tennguoigiamsat, string chucvu, string capbac)
        {
            var magsParameter = mags != null ?
                new ObjectParameter("Mags", mags) :
                new ObjectParameter("Mags", typeof(string));
    
            var tennguoigiamsatParameter = tennguoigiamsat != null ?
                new ObjectParameter("Tennguoigiamsat", tennguoigiamsat) :
                new ObjectParameter("Tennguoigiamsat", typeof(string));
    
            var chucvuParameter = chucvu != null ?
                new ObjectParameter("Chucvu", chucvu) :
                new ObjectParameter("Chucvu", typeof(string));
    
            var capbacParameter = capbac != null ?
                new ObjectParameter("Capbac", capbac) :
                new ObjectParameter("Capbac", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insert_giamsat", magsParameter, tennguoigiamsatParameter, chucvuParameter, capbacParameter);
        }
    
        public virtual int delete_giamsat(string mags)
        {
            var magsParameter = mags != null ?
                new ObjectParameter("Mags", mags) :
                new ObjectParameter("Mags", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("delete_giamsat", magsParameter);
        }
    
        public virtual int update_giamsat(string mags, string tennguoigiamsat, string chucvu, string capbac)
        {
            var magsParameter = mags != null ?
                new ObjectParameter("Mags", mags) :
                new ObjectParameter("Mags", typeof(string));
    
            var tennguoigiamsatParameter = tennguoigiamsat != null ?
                new ObjectParameter("Tennguoigiamsat", tennguoigiamsat) :
                new ObjectParameter("Tennguoigiamsat", typeof(string));
    
            var chucvuParameter = chucvu != null ?
                new ObjectParameter("Chucvu", chucvu) :
                new ObjectParameter("Chucvu", typeof(string));
    
            var capbacParameter = capbac != null ?
                new ObjectParameter("Capbac", capbac) :
                new ObjectParameter("Capbac", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("update_giamsat", magsParameter, tennguoigiamsatParameter, chucvuParameter, capbacParameter);
        }
    
        public virtual ObjectResult<spgettablehvkl_Result> spgettablehvkl(string maHV)
        {
            var maHVParameter = maHV != null ?
                new ObjectParameter("MaHV", maHV) :
                new ObjectParameter("MaHV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spgettablehvkl_Result>("spgettablehvkl", maHVParameter);
        }
    
        public virtual ObjectResult<spgettablehvplkl_Result> spgettablehvplkl(string maHV)
        {
            var maHVParameter = maHV != null ?
                new ObjectParameter("MaHV", maHV) :
                new ObjectParameter("MaHV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spgettablehvplkl_Result>("spgettablehvplkl", maHVParameter);
        }
    
        public virtual ObjectResult<spgetMaHV_Result> spgetMaHV(string maHV)
        {
            var maHVParameter = maHV != null ?
                new ObjectParameter("MaHV", maHV) :
                new ObjectParameter("MaHV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spgetMaHV_Result>("spgetMaHV", maHVParameter);
        }
    
        public virtual ObjectResult<getPLKL_DaiDoi_2_Result> getPLKL_DaiDoi_2()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getPLKL_DaiDoi_2_Result>("getPLKL_DaiDoi_2");
        }
    
        public virtual ObjectResult<getPLKL_Lop_Result> getPLKL_Lop()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getPLKL_Lop_Result>("getPLKL_Lop");
        }
    
        public virtual ObjectResult<spgettablephaihvplkl_Result> spgettablephaihvplkl(string maHV)
        {
            var maHVParameter = maHV != null ?
                new ObjectParameter("MaHV", maHV) :
                new ObjectParameter("MaHV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spgettablephaihvplkl_Result>("spgettablephaihvplkl", maHVParameter);
        }
    }
}
