//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanlyKiluat
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quanly
    {
        public string MaQL { get; set; }
        public string Matkhau { get; set; }
        public string Hoten { get; set; }
        public string Chucvu { get; set; }
        public string Capbac { get; set; }
        public string MaDD { get; set; }
    
        public virtual Daidoi Daidoi { get; set; }
    }
}
